name: Deploy to VPS

on:
  push:
    branches:
      - master  # Ou la branche de votre choix

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.0
      with:
        host: 157.173.118.165  # Votre adresse IP de VPS
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."  # Répertoire source sur GitHub
        target: "/var/www/my-apps"  # Chemin de destination sur le VPS
