name: Deploy to VPS

on:
  push:
    branches:
      - main  # Déclenche le déploiement à chaque fois qu'il y a un push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          # Naviguer vers votre dossier de projet sur le VPS
          cd /home/my_sites

          # Mettre à jour le code source
          git pull origin main

          # Rebuild and restart your services (e.g., Docker)
          #docker-compose down
          #docker-compose up -d --build
        EOF
